workspace:
  base: /go/
  path: src/github.com/spaceshuttl/coffer

pipeline:
  build:
    image: golang:${TAG}
    commands:
      - mkdir /go/bin
      - curl https://glide.sh/get | sh
      - make install
      - make test
      - make build

  notify:
    image: plugins/slack
    webhook: $SLACK_WEBHOOK
    channel: coffer
    username: drone


matrix:
  TAG:
    - 1.7.4
    - 1.8
    - latest
