pipeline:
  build:
    image: golang
    commands:
      - make install
      - make test
      - make build
  slack:
    image: plugins/slack
    webhook: $SLACK_WEBHOOK
    channel: coffer
    username: drone
